### ISSUE TITLE
Feature request: Autocomplete Overflow

### ISSUE THREAD

**Issue by jacquesuhlemann** [JaleelB/shadcn-tag-input#6]
Currently the autocomplete shows all existing tags, the list can become very long.

It would be perfect to use autocomplete in an overflow. Perhaps even in a popover so that other elements underneath are not moved too far.

Great work and many thanks

**Comment by JaleelB** [comment]
Hey @jacquesuhlemann. Thanks for the love, I appreciate it. 

If I am understanding what you are saying, then a workaround to that issue is setting a max with on the container the autocomplete input is in.

The popover feature is a good feature idea. I am currently working on a few iterations. I'll push what I have in a bit

**Comment by eliza921** [comment]
I have tried with the Popover component and it was almost good! The only problem I noticed was when attempting to select the first tag it required two-clicks, which is not the intended behavior.

As a workaround, I tried wrapping the <CommandList> element with a <ScrollArea> component from shadcn.

**Comment by JaleelB** [comment]
@jacquesuhlemann  @eliza921 Thank you for your valuable feedback and suggestions regarding the Tag Input component.  I've gone ahead and implemented the features you requested! Try it out and let me know what you think

https://github.com/JaleelB/shadcn-tag-input/assets/78449846/ab0cbf96-8a44-4326-a759-f1111c5f073e
