### ISSUE TITLE
Autocomplete feature not working properly

### ISSUE THREAD

**Issue by eliza921** [JaleelB/shadcn-tag-input#7]
I've noticed that the autocomplete is not working properly. After the second character input, all the options disappear. I've been trying to debug this issue, but so far, I haven't had any luck in identifying the root cause.

Any guidance or suggestions would be greatly appreciated.

Despite this issue, I find the tool very useful and appreciate the effort put into developing it.
Thanks a lot.

**Comment by eliza921** [comment]
Apparently, this has fixed it!

```diff
-<CommandItem key={uuid()} className={`py-0 ${maxTags !== undefined && tags.length >= maxTags ? "cursor-not-allowed" : "cursor-pointer"}}>
+<CommandItem key={optionObj.text} className={`py-0 ${maxTags !== undefined && tags.length >= maxTags ? "cursor-not-allowed" : "cursor-pointer"}}>
```

**Comment by JaleelB** [comment]
> Apparently, this has fixed it!
> 
> ```diff
> -<CommandItem key={uuid()} className={`py-0 ${maxTags !== undefined && tags.length >= maxTags ? "cursor-not-allowed" : "cursor-pointer"}}>
> +<CommandItem key={optionObj.text} className={`py-0 ${maxTags !== undefined && tags.length >= maxTags ? "cursor-not-allowed" : "cursor-pointer"}}>
> ```

Thank you for bringing this issue to our attention and for sharing your solution. It's great to hear that changing the key in the <CommandItem> from uuid() to optionObj.text resolved the autocomplete problem. This issue was quite weird. I tried recreating it but didn't get the same results. Will keep an eye out for this though.
